CREATE TABLE inscricoes_retiro (
    id BIGSERIAL PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    idade INTEGER,
    responsavel_nome VARCHAR(255),
    responsavel_contato VARCHAR(255),
    documento_identificacao VARCHAR(255) NOT NULL,
    contato_individual VARCHAR(255) NOT NULL,
    endereco TEXT NOT NULL,
    tamanho_camisa VARCHAR(32) NOT NULL,
    emergencia_nome VARCHAR(255) NOT NULL,
    emergencia_parentesco VARCHAR(255) NOT NULL,
    emergencia_contato VARCHAR(255) NOT NULL,
    alergias TEXT,
    necessidades_especiais TEXT,
    participou_retiro BOOLEAN NOT NULL,
    comunidade_origem VARCHAR(255) NOT NULL,
    dons_habilidades TEXT NOT NULL,
    forma_pagamento VARCHAR(20) NOT NULL,
    comprovante_pagamento VARCHAR(512),
    consentimento_imagem BOOLEAN NOT NULL,
    consentimento_dados BOOLEAN NOT NULL
);
